//db.movies.insert({_id:1, title : 'Fight Club', writer : 'Chuck Palahniuk', year : 1999, actors : ['Brad Pitt','Edward Norton']})
//db.movies.insert({_id:2, title : 'Pulp Fiction', writer : 'Quentin Tarantino', year : 1994, actors : ['John Travolta','Uma Thurman']})
//db.movies.insert({_id:3, title : 'Inglorious Basterds', writer : 'Quentin Tarantino', year : 2009, actors : ['Brad Pitt', 'Diane Kruger', 'Eli Roth']})
//db.movies.insert({_id:4, title : 'The Hobbit: An Unexpected Journey', writer : 'J.R.R Tolkien', year : 2012, franchise:'The Hobbit'})
//db.movies.insert({_id:5, title : 'The Hobbit: The Desolation of Smaug', writer : 'J.R.R Tolkien', year : 2013, franchise:'The Hobbit'})
//db.movies.insert({_id:6, title : 'The Hobbit: the Battle of the Five Armies', writer : 'J.R.R Tolkien', year : 2012, franchise:'The Hobbit'})
//db.movies.insert({_id:7, title : 'Pee Pee Herman´s Big Adventure'})
//db.movies.insert({_id:8, title : 'Avatar'})
//db.movies.find()
//db.movies.find({writer: "Quentin Tarantino"})
//db.movies.find({actors: "Brad Pitt"})
//db.movies.find({franchise: "The Hobbit"})
//db.movies.find({$and: [{year: {$gt: 1900}}, {year: {$lt: 2000}}]})
//db.movies.find({$and: [{year: {$gt: 2000}}, {year: {$lt: 2010}}]})
//db.movies.update({_id:4}, {synopsis: 'A reluctant hobbit, Bilbo Baggins, sets out to the Lonely Mountain with a spirited group of dwarves to reclaim their mountain home - and the gold within it - from the dragon Smaug.'})
//db.movies.update({_id:5}, {synopsis: 'The dwarves, along with Bilbo Baggins and Gandalf the Grey, continue their quest to reclaim Erebor, their homeland, from Smaug. Bilbo Baggins is in possession of a mysterious and magical ring.'})
//db.movies.update({_id:2}, {$push: {actors: 'Samuel L. Jackson'}})
//db.movies.find({$text:{$search:'Bilbo'}})
//db.movies.find({$text: {$search: "Gandalf"}})
//db.movies.find({$text: {$search: "Bilbo -Gandalf"}})
//db.movies.find({$text: {$search: "dwarves hobbit"}})
//db.movies.find({$text: {$search: "gold dragon"}})
//db.movies.remove({title: 'Pee Pee Herman´s Big Adventure'})
//db.movies.remove({title: "Avatar"})
